FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends git

COPY build/llmperf /app/llmperf
COPY requirements.txt /app/requirements.txt

RUN apt-get update

RUN pip install --no-cache-dir -e /app/llmperf && \
    pip install -r /app/requirements.txt && \
    pip install docker

COPY main.py /app/main.py

RUN chmod +x /app/main.py

ENTRYPOINT ["python", "/app/main.py"]
