name: continuous_integration

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
          python3 \
          python3-pip \
          ninja-build \
          libopenblas-dev \
          build-essential \
          pkgconf
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0
      - name: Cache Python packages
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[all]"
      - name: Start a server
        run: |
          make docker
          mkdir -p models
          curl -L https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q5_K_S.gguf \
          -o models/Llama-3.2-1B-Instruct-Q5_K_S.gguf
          docker run \
            -v C:/Users/evsei/PycharmProjects/NekkoAPI/models:/app/models \
            -v C:/Users/evsei/PycharmProjects/NekkoAPI/examples/settings.json:/app/settings.json \
            --cap-add SYS_RESOURCE \
            -p 8000:8000 \
            -e CONFIG_FILE=settings.json \
            nekko-api
      - name: Run tests
        run: python3 -m pytest --full-trace -v
