name: continuous_integration

on:
  pull_request: # temp
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Image tag
        required: true
        default: latest

concurrency:
  group: ${{ github.workflow }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aifoundry-org/nekko-api

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ inputs.tag || 'test' }}
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/simple/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
